modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"

[[mods]]
modId = "bocchium"
version = "${version}"
displayName = "Bocchium"
authors="TeamPotato"
description = '''
Bocchi The Bedrock!
'''

[[dependencies.bocchium]]
    modId = "rubidium"
    mandatory = true
    versionRange = "[0.6.2b,)"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.bocchium]]
    modId = "papi"
    mandatory = true
    versionRange = "[0.0.1,)"
    ordering = "NONE"
    side = "CLIENT"