modLoader = "javafml"
loaderVersion = "[36,)"
license = "LGPL-v3"

[[mods]]
modId = "bocchium"
version = "${version}"
displayName = "Bocchium"
authors="TeamPotato"
description = '''
Bocchi The Bedrock!
'''